#!/usr/bin/perl

package Bot;
use base qw(Bot::BasicBot);
use warnings;
use strict;
use Try::Tiny;
use Config::Simple

$SIG{'INT'} = \&cleanquit;
$SIG{'TERM'} = \&cleanquit;

use sorbot::Database;
my $cfg = new Config::Simple('/var/lib/adom/etc/config');

print "This is ADOM DB Bot\n";

my %help = map{$_=>1}
    qw{help h commands instructions guide manual functions info man};

my $usage = "Usage: \@[mi] name fragment | \@[mi] /regex/";

my $bot = Bot->new(
  server => $cfg->param('IRCSERV'),
  channels => [ $cfg->param('IRCCHAN') ],
  nick => 'dbbot',
  ssl => 1,
  port => 6697,
  quit_message => "Aieee!",
);

sub said {
  my $self = shift;
  my $message = shift;
  my $body = $message->{body};
  my $query;
  try {
      (($query) = $body =~ /^\@m\s+(.*)/) && return $self->reply($message, sorbot::Database::lookup('sorbot::MonsterDb', $query));
      (($query) = $body =~ /^\@i\s+(.*)/) && return $self->reply($message, sorbot::Database::lookup('sorbot::ItemDb', $query));
      ($body =~ /^@(.*)/ && $help{$1}) && return $self->reply($message, $usage);
  } catch {
      return $self->reply($message, $_);
  };
}
sub cleanquit() { 
  print STDERR "Caught signal, shutting down\n";
  $bot->shutdown( $bot->quit_message() ); 
  sleep 3;
  exit;
}
$bot->run();

