#!/bin/bash

# $sage = enabled/disabled -- whether sage should be used
# $adom_ver = 100/111/etc/lea/swap/120p3/... -- adom version
# $ttyq - enabled/disabled -- whether tty recording should be used
# $chal - etr/ste/... -- challenge game mode
ulimit -c unlimited

if [ "$ttyq" = "enabled" ]; then
	echo ""
	python /var/lib/adom/server/ttyrecord.py
	res="$?"

	if (( "$res" == "1" )); then
		exit
	fi
fi

python /var/lib/adom/server/check_term.py
touch /var/lib/adom/tmp/sockets/$USER
umask 013

if [ -e ${HOME}/adom_dirty ]; then
    echo "Your last ADOM run ended abnormally. Checking for backups."
    echo
    
    FILES=`ls ${HOME}/.adom.data/backup`
    if [ "$FILES" = "" ]; then
        echo "You don't have backups to restore."
        sleep 2
    else
        output=""
        restoreq=""
        FBAK="${HOME}/.adom.data/backup"
        FACT="${HOME}/.adom.data/savedg"
        for save in $FILES
        do
            if [ -f ${FACT}/${save} ]; then
              MDB=$(md5sum ${FBAK}/${save}|awk '{print $1}')
              MDA=$(md5sum ${FACT}/${save}|awk '{print $1}')
              LSB=$(ls --time-style=+"%F %T" -l ${FBAK}/${save} | awk '{print "Size: "$5"b, modified "$6" "$7}')
              LSA=$(ls --time-style=+"%F %T" -l ${FACT}/${save} | awk '{print "Size: "$5"b, modified "$6" "$7}')
              if [ "${MDB}" != "${MDA}" ]; then
                restoreq+=" ${save}"
    	        output+="+ ${save} exists in both the backup and live folder and are different!\n"
                output+="  \` ACTIVE: ${LSA}\n"
                output+="  \` BACKUP: ${LSB}\n"
              fi
            else
              restoreq+=" ${save}"
    	      output+="+ ${save}\n"
              output+=" \`- Is MISSING from the live folder (and likely the one you want)\n"
            fi
        done
        if [ "${restoreq}" != "" ]; then 
          echo -e "$output"
          for game in $restoreq; do
	      while true; do
      	        read -e -p "Do you wish to restore ${game} (Y/N)? " ANS
                case $ANS in
		    Y | y) 
			echo -n "Restoring ${game} backup..."
			cp ${FBAK}/${game} ${FACT}/${game}
			echo " Done!"
			break
			;;
		    
		    N | n)
			echo "${game} backup not restored!"
			break
			;;
		    
		    *)
			continue
			;;
		    
	        esac
             done
          done
        sleep 5
        else echo "No differences between live and backup saves found."
        fi
    fi
fi

res="0"
> ${HOME}/adom_dirty
chalstr=""
if [ "${chal}" != "" ]; then chalstr="-${chal}"; fi
wrapperstr="/var/lib/adom/bin/adom-${adom_ver}${chalstr}"
# If DEBUG, or missing wrapper, run ADOM straight
if [ -f ${HOME}/debug ]  || [ ! -f /var/lib/adom/bin/adom-$adom_ver ]; then
  /var/lib/adom/bin/adom-$adom_ver-bin 
  res="$?"
else 
  if [ "$sage" = "enabled" ]; then
    $wrapperstr --enable-sage
    res="$?"
  else
    $wrapperstr
    res="$?"
  fi
fi
find ${HOME} -name core -exec chmod 644 '{}' \;
chmod 755 ${HOME}/.adom.data/savedg
chmod 775 ${HOME}/ttyrecs
find ${HOME} -type f -name "*.svg" -exec chmod 644 '{}' \;
# ttyrecs group writable so adomown can delete old ones
find ${HOME} -type f -name "ttyrec-*" -exec chmod 664 '{}' \;

if (( ! ( ("$res" == "0") || ("$res" == "2") ) )); then
    echo "Damnit! It seems ADOM has exited with an abnormal exit code $res"
    echo "Backups may exist; re-launch for details"
    sleep 10
else
    rm ${HOME}/adom_dirty
#    rm -f ${HOME}/cryopid_image
    svdir=${HOME}/.adom.data/savedg
    bkdir=${HOME}/.adom.data/backup
    SAVES=`ls ${svdir}`
    for stale in `comm -2 -3 <(ls ${bkdir}) <(ls ${svdir})`; do
	rm ${bkdir}/${stale}
    done

    for file in $SAVES
    do	
        [ "${svdir}/$file" -nt "${bkdir}/$file" ] &&
	    cp -p ${svdir}/$file ${bkdir}/
    done
fi

for newflg in $(find ${HOME} -maxdepth 1 -name '*.flg'); do
  /var/lib/adom/server/record-flg.pl "${newflg}" "$adom-ver"
done
find ${HOME} -maxdepth 1 -name '*.flg' -exec chmod 644 '{}' \; -exec mv '{}' ${HOME}/flgs \;
find /var/lib/adom/tmp/player_locations -type f -user $USER -mmin +29 -delete 
rm -f /var/lib/adom/tmp/sockets/$USER
rm -f /var/lib/adom/${adom_ver}/ADOM_HS.LCK /var/lib/adom/${adom_ver}/adom.err
rm -f $HOME/.adom.data/.adom.prc
