#!/bin/bash
PATH=$PATH:/usr/local/bin
tmux new-session -d -s "adom-bots" -x 80 -y 26 '/var/lib/adom/server/update_hiscore.sh'
tmux new-window 'python /var/lib/adom/server/adombot.py irc.freenode.net:6697 AnnounceBot "#adom" "Public ADOM server" True'
tmux new-window 'cd /var/lib/adom/dbbot/; perl /var/lib/adom/dbbot/sorbot/bot'
