#!/bin/bash

mkdir -p ${HOME}/.adom.data/

if [[ "${EDITOR}x" == "x" ]]; then
  export EDITOR=rnano
fi

function notfound {
  echo -e "That config file doesn't (yet) exist. Please start ADOM once or Sage twice,\nthen return to this screen."
  sleep 3
}

while true
do
    clear

    echo "Welcome to the ADOM configuration editor menu. Here you can edit your ADOM"
    echo -e "configuration with the \e[1m${EDITOR}\e[0m editor."

    echo "Please note that you will need to switch the ADOM version in the main menu in"
    echo "order to edit configurations for other versions (this does not apply to the SSH"
    echo "SSH authorized_keys file)."
    echo
    echo "In nano, press Ctrl+O to save your new config and press Ctrl+X to exit."
    echo
    echo "Select the config you wish to edit:"
    echo
    echo "  1 - adom.cfg, main ADOM configuration file"
    echo "  2 - adom.kbd, ADOM keymap configuration file"
    echo "  3 - sage.cfg, ADOM Sage main configuration file"
    echo "  4 - sage.msg, ADOM Sage message configuration file"
    echo "  5 - sage.kbd, ADOM Sage keymap configuration file"
    echo
    echo "  6 - Copy config files to current ADOM version"
    echo
    echo "  7 - ~/.ssh/authorized_keys, authorized SSH RSA/DSA public keys"
    echo
    echo "  8 - toggle vim/nano for text editing"
    echo
    echo "  9 - quit"

    read -e -p "> " command
    case $command in
	
	1)
            if [ -f ${HOME}/.adom.data/.adom.cfg ]; then
  	      ${EDITOR} "${HOME}/.adom.data/.adom.cfg"
            elif [ -f ${HOME}/.adom.data/adom.cfg ]; then
              ${EDITOR} "${HOME}/.adom.data/adom.cfg"
            else
              notfound
            fi
	    continue
	    ;;
	
	2)
            if [ -f ${HOME}/.adom.data/.adom.kbd ]; then
               ${EDITOR} "${HOME}/.adom.data/.adom.kbd"
            elif [ -f "${HOME}/.adom.data/adom.kbd" ]; then
               ${EDITOR} "${HOME}/.adom.data/adom.kbd"
            else
              notfound
            fi
	    continue
	    ;;
	
	3)
            if [ -f "${HOME}/.adom.data/sage.cfg" ]; then
  	      ${EDITOR} "${HOME}/.adom.data/sage.cfg"
            else
              notfound
            fi
	    continue
	    ;;
	
	4)
            if [ -f "${HOME}/.adom.data/sage.msg" ]; then
	      ${EDITOR} "${HOME}/.adom.data/sage.msg"
            else
              notfound
            fi
	    continue
	    ;;
	
        5)
            if [ -f "${HOME}/.adom.data/sage.kbd" ]; then
              ${EDITOR} "${HOME}/.adom.data/sage.kbd"
            else
              notfound
            fi
            continue
            ;;
	6)
	    /var/lib/adom/server/copy_conf	
	    continue
	    ;;
	7)
	    ${EDITOR} "${HOME}/.ssh/authorized_keys"
	    continue;
	    ;;
        8)
           NEWED='rnano'
           if [ "${EDITOR}x" == "rnanox" ]; then
              NEWED='rvim'
           fi
           export EDITOR=${NEWED}
           grep EDITOR ${HOME}/.profile > /dev/null 2>&1
           if [[ $? -gt 0 ]]; then
             echo "export EDITOR=${NEWED}" >> ${HOME}/.profile
           else
             sed -e "s/export EDITOR=.*/export EDITOR=${NEWED}/" ${HOME}/.profile >> /tmp/profile.$$
             mv /tmp/profile.$$ ${HOME}/.profile
           fi
           continue
           ;;            
	9|q|z)
	    exit
	    ;;
	*)
	    echo "Erroneous selection!"
	    sleep 2
	    continue
	    ;;
    esac
done
