#!/bin/bash

mkdir -p ${HOME}/.adom.data/

while true
do
    clear

    echo "Welcome to the ADOM configuration editor menu. Here you can edit your ADOM"
    echo "configuration with the nano editor."

    echo "Please note that you will need to switch the ADOM version in the main menu in"
    echo "order to edit configurations for other versions (this does not apply to the SSH"
    echo "SSH authorized_keys file)."
    echo
    echo "Press Ctrl+O to save your new config.  Press Ctrl+X to exit nano."
    echo
    echo "Select the config you wish to edit:"
    echo
    echo "  1 - .adom.cfg, main ADOM configuration file"
    echo "  2 - .adom.kbd, ADOM keymap configuration file"
    echo "  3 - sage.cfg, ADOM Sage main configuration file"
    echo "  4 - sage.msg, ADOM Sage message configuration file"
    echo "  5 - sage.kbd, ADOM Sage keymap configuration file"
    echo
    echo "  6 - Copy config files to current ADOM version"
    echo
    echo "  7 - ~/.ssh/authorized_keys, authorized SSH RSA/DSA public keys"
    echo
    echo "  8 - quit"

    read -e -p "> " command
    case $command in
	
	1)
	    nano --restricted "${HOME}/.adom.data/.adom.cfg"
	    continue
	    ;;
	
	2)
	    nano --restricted "${HOME}/.adom.data/.adom.kbd"
	    continue
	    ;;
	
	3)
	    nano --restricted "${HOME}/.adom.data/sage.cfg"
	    continue
	    ;;
	
	4)
	    nano --restricted "${HOME}/.adom.data/sage.msg"
	    continue
	    ;;
	
        5)
            nano --restricted "${HOME}/.adom.data/sage.kbd"
            continue
            ;;
	6)
	    /var/lib/adom/server/copy_conf	
	    continue
	    ;;
	7)
	    nano --restricted "${HOME}/.ssh/authorized_keys"
	    continue;
	    ;;
	8|q|z)
	    exit
	    ;;
	*)
	    echo "Erroneous selection!"
	    sleep 2
	    continue
	    ;;
    esac
done
