#!/bin/bash
. /var/lib/adom/etc/config

CFGBASE="${HOME}/adom.data-"
CFGTO="${HOME}/.adom.data"

CHALS="etr ste iro brm lth none quit"
VERSIONS="100 111 lea swp"
for i in $(seq ${MIN_PRE} ${MAX_PRE}); do
    VERSIONS+=" 120p${i}"
done
VERSIONS+=" quit"
echo "Copying TO active version: ${adom_ver}-${chal}"
echo "Which version to copy FROM?"
select FROM in $VERSIONS; do 
    if [[ ${REPLY} == "quit" ]] || [[ ${FROM} == "quit" ]]; then break; 
    elif [[ -z ${FROM} ]]; then continue; 
    fi
    echo "Copying FROM version ${FROM}"
    echo "Copy FROM a challenge game (default: ${chal:-"no"})?"
    CHALF=""
    i=1
    for n in $CHALS; do
      echo -n "$i) $n  "
      ((i++))
    done
    echo ""
    while [ 1 ]; do
        read -e -p "#? " CHALF
        CHALF=${CHALF:-${chal}} 
        case $CHALF in
          4|quit|q)
            break
            ;;
          1|etr) CHALF="etr"; break;; 
          2|ste) CHALF="ste"; break;; 
          3|iro) CHALF="iro"; break;;
          4|brm) CHALF="brm"; break;;
          5|lth) CHALF="lth"; break;;
          6|none) CHALF=""; break;; 
          "") CHALF=${chal}; break;;
          *)
            echo "Invalid!"
            continue
            ;;
        esac
    done
    if [[ "${CHALF}" != "" ]]; then
      echo "Using challenge game ${CHALF}"
      FROM="${FROM}/${CHALF}"
    fi
    mkdir -p ${CFGBASE}${FROM}/${FILE} ${CFGTO}/${FILE}
    for FILE in adom.kbd adom.cfg .adom.kbd .adom.cfg sage.cfg sage.kbd sage.msg; do
        if [ -f ${CFGBASE}${FROM}/${FILE} ]; then
            echo "Copying ${FILE}..."
            cp -pi ${CFGBASE}${FROM}/${FILE} ${CFGTO}/${FILE}
            PRER=$(echo $adom_ver | cut -f2 -d'p')
            if (( $PRER >= 11 )) && [[ "${FILE}" == ".adom.kbd" || "${FILE}" == ".adom.cfg" ]]; then
                mv ${CFGTO}/${FILE} ${CFGTO}/${FILE#.}
            fi
        fi
    done
    break
done

echo "Done."
sleep 4
