#!/bin/bash

if ! $(tty -s); then echo "No TTY found. Be sure you're a real person coming from a real terminal and that you're not supplying your own command. Bailing out."; exit 1; fi
if [ "${TERM}x" == "dumbx" ] || [ "${TERM}x" == "x" ]; then export TERM=vt100; fi

clear

python /var/lib/adom/server/registration_check.py --checkonly
ret="$?"

if [ "$ret" == "1" ]; then
  sleep 60
  exit
fi

echo "Welcome to the ADOM player account creation script on this Ancardia"
echo "ADOM server. Follow the instructions to create your account, then"
echo "use your SSH client again and log in with your newly created account!"
echo ""
echo "IMPORTANT NOTICE: only three registrations per IP allowed every day!"
echo ""
echo "Please enter your desired username or press control-C to abort."
echo "-- ONLY LOWERCASE LETTERS ALLOWED! --"
echo ""
echo "Desired username: "

NAME=""
USERS=`wc -l < /etc/passwd`

if (( $USERS < 4000 )); then
    until [ ! $NAME == "" ]; do
            read -e -p "> " NAME
            if [[ ! ${NAME} =~ ^[a-z][-a-z0-9_]{0,30}$ ]]; then
              echo "Invalid username or name already taken, try again"
              NAME=""
            fi
            grep -q "^${NAME},$" disallowedusernames.csv
            if [ $? -eq 0 ]; then
              echo "Invalid username or name already taken, try again"
              NAME=""
            fi
            id "$NAME" > /dev/null 2>&1
            if [ $? -eq 0 ]; then
              echo "Invalid username or name already taken, try again"
              NAME=""
            fi
    done
    
    /var/lib/adom/server/adom_adduser.sh "$NAME"
    python /var/lib/adom/server/registration_check.py
    sleep 60    

else
    echo "Sorry, user limit reached. No new users may be created!"
    sleep 30
fi
